version: "1.0.0"
services:
  planning-service:
    build: ./planning-service
    depends_on:
      - rabbitmq
    ports:
      - "8081:8080"

  registry-service:
    build: ./registry-service
    depends_on:
      - rabbitmq
    ports:
      - "8082:8080"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password